double YW(double Y);
double WY(double W);
double YWM(double Y, double W);
double YWB(double Y, double W);
double YWN(double Y, double W);
double YWH(double Y, double W);
double YWS(double Y, double W);
double YWDYB(double Y, double W);
double YWDRB(double Y, double W);
double YWDLN(double Y, double W);
double YWYDN(double Y, double W);
double YWDR(double Y, double W);
double YHW(double Y, double H);
double YSW(double Y, double S);
double YGM(double Y, double G);
double WGM(double W, double G);
double YGB(double Y, double G);
double WGB(double W, double G);
double YGN(double Y, double G);
double WGN(double W, double G);
double YGH(double Y, double G);
double WGH(double W, double G);
double YGS(double Y, double G);
double WGS(double W, double G);
double YHG(double Y, double H);
double YSG(double Y, double S);